### ISSUE TITLE
Inconsistent color in new messages received

### ISSUE THREAD

**Issue by Pratham-T** [Pratham-T/arcticnight-thunderbird#1]
## Test environment
Thunderbird version: 128
OS: Ubuntu 24.04 LTS

## Description

The subject color of new messages received has a different color than the sender's name. 

Reason: Subject line uses a separate variable `--new-subject-color` under a separate css property:

```css
#threadTree[rows="thread-card"] {
  & .card-layout {
    &[data-properties~="unread"] {
      &[data-properties~="new"] {
        & .subject {
          color: var(--new-subject-color);
        }
      }
    }
  }
}
```

The mail replies icon in a thread which has new messages has a different color than the rest of the text of "x replies". This is correct when the thread has changed from "new" messages to "unread" messages.

Reason: Again, uses its own css property

```css
#threadTree[rows="thread-card"] {
  & .card-layout {
    &[data-properties~="hasNew"] {
      & .replies-icon, & .thread-replies {
        color: var(--new-color);
      }
    }
  }
}
```

Ultimately, the core reason is, need to set properties properly for all of "unread", "new", "hasUnread" and "hasNew" properties. Also need to ponder, do we need separate colors for new and unread, or treat them same visually?
